appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PGpmVfEDzvypVgbIoGPEA8KrtAU3hfh5xZssdsXrHCg+c/dbcC2AQdnBPIB6/8XbeIuzqn2jRSM+Zurh5Mp1J5pHbbEA1qNxMC1IsEhFLgvFCoXrVhXOHm4Q+59lCclIgRogLt032lyrDWOU7iEEJotBjLWjt7S8If1GNUd31Ei1vbT6Yhq2ML5a6N6vPzLm0/62B0DouMId9VkTKMwaT6hkWwHPQpm/zkJ0OjMRev/lXjXllYn0+nVcAKGO4rUfysJCcjzMYhKfitEshzxZQvz1QFsjjV5XwAsVp9Jov2CDWOhlgQpKhh9odrXjKToEawwqSBOWz4IDfbUE1lmxZJx3dEbumcLkOsPnGvJr/HWlIziubfkAD7AohurPHQ3obxlne5jpgU4W+rJLxWYD5VDLfM2Q3pVBJgWkHT61jpypn93eEr1RDFnF1IGVn21KBVq7W3T7bnIFZinfzryHRD00KaQZDJBhy7VO2hgvEe1HpHz1XZ6hdo9OcivxpW3t9InE0r0F/kGhD48NC135Z6KnjDxJ9vh7q8e4W+jMdNgcCbb1JSg5fDaBhzwcoyjuw6UGB+LGPpp0eyP8V6DEixQ9cAipnUOpEUneq1NZjDqKXJVE1SmBuKiahRL+KLrN+PVICono3dp572fFTVoyPuTBPosJcZWtCO6ncQqdxLk=
